services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: carona-nginx
    ports:
      - '80:80'
      - '81:81'  
      - '443:443'
    volumes:
      - ./data/nginx/data:/data
      - ./data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - carona-network
  carona-db:
    image: postgres
    container_name: carona-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data/:/var/lib/postgresql
    networks:
      - carona-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: carona-cloudfare
    command: tunnel run --token ${TOKEN_CLOUDFARE}
    restart: unless-stopped
    networks:
    - carona-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: carona-pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    networks:
      - carona-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: carona-streamlit
    networks:
      - carona-network
    expose:
      - "8501"
    environment:
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false

  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile.fastapi
    container_name: carona-fastapi
    ports:
      - 8000:80
    networks:
      - carona-network

networks:
  carona-network:
    name: carona-network
    driver: bridge
    